import { Exercise } from '../models/types';

export const DEFAULT_EXERCISES: Exercise[] = [
  // ============================================
  // PERNAS
  // ============================================
  {
    id: 'leg-press-001',
    name: 'Leg Press (máquina)',
    muscleGroup: 'pernas',
    description: 'Pressionar a plataforma com os pés, controlando a descida. Amplitude completa sem forçar a lombar.',
    isLumbarSafe: true,
    isKneeSafe: false,
    type: 'máquina',
    instructions: 'Ajustar o banco para 90-100º. Pés na largura dos ombros. Descer controlado até 90º de flexão do joelho. Nunca travar com as costas.',
    substitutions: ['extensao-pernas-001', 'agachamento-goblet-001'],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'extensao-pernas-001',
    name: 'Extensão de Pernas (máquina)',
    muscleGroup: 'pernas',
    description: 'Isolamento do quadríceps. Excelente para fortalecimento sem carga lombar.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Ajustar o rolete acima do tornozelo. Estender as pernas completamente, contrair o quadríceps 2 segundos no topo. Descer controlado.',
    substitutions: ['leg-press-001'],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'flexao-pernas-001',
    name: 'Flexão de Pernas (máquina)',
    muscleGroup: 'pernas',
    description: 'Isolamento dos isquiotibiais. Fundamental para equilíbrio muscular e proteção do joelho.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Ajustar o rolete abaixo do tornozelo. Flexionar o joelho até 90º. Manter quadril colado ao banco. Nunca subir o glúteo.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'adutores-001',
    name: 'Adutores (máquina)',
    muscleGroup: 'pernas',
    description: 'Fortalecimento da face interna da coxa. Importante para estabilidade do quadril e prevenção de lesões.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Ajustar a abertura confortavelmente. Contrair as coxas uma contra a outra, segurar 2 segundos. Descer controlado.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'abducoes-001',
    name: 'Abduções (máquina)',
    muscleGroup: 'pernas',
    description: 'Fortalecimento do glúteo médio. Essencial para estabilidade do quadril e postura.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Ajustar os roletes exteriores aos joelhos. Abrir as pernas contra a resistência, controlar na descida.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'panturrilha-001',
    name: 'Panturrilha em Pé (máquina)',
    muscleGroup: 'pernas',
    description: 'Fortalecimento da panturrilha. Importante para equilíbrio, impulsão no squash e prevenção de quedas.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Calcanhares para fora, subir o mais alto possível, baixar abaixo da plataforma para alongar. Nunca travar os joelhos.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'agachamento-goblet-001',
    name: 'Agachamento Goblet (peso livre)',
    muscleGroup: 'pernas',
    description: 'Agachamento com haltere ao peito. Menos carga lombar que o agachamento tradicional.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'peso livre',
    instructions: 'Segurar um haltere verticalmente ao peito. Pés na largura dos ombros. Descer até coxas paralelas ao chão. Costas neutras.',
    substitutions: ['leg-press-001'],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'step-up-001',
    name: 'Step Up com Haltere',
    muscleGroup: 'pernas',
    description: 'Subir a um banco com um haltere em cada mão. Excelente para equilíbrio, coordenação e força funcional.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'peso livre',
    instructions: 'Frente a um banco. Subir com um pé, trazer o outro ao lado, descer controlado. Alternar pernas. Costas retas.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },

  // ============================================
  // COSTAS
  // ============================================
  {
    id: 'puxada-frontal-001',
    name: 'Puxada Frontal (máquina)',
    muscleGroup: 'costas',
    description: 'Puxar a barra até ao peito. Excelente para dorsais, sem carga lombar.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Ajustar o rolete das coxas. Puxar a barra até ao peito superior, contrair as escápulas. Descer controlado. Nunca balançar.',
    substitutions: ['remada-sentada-001'],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'remada-sentada-001',
    name: 'Remada Sentada (máquina)',
    muscleGroup: 'costas',
    description: 'Puxar o cabo em direção ao umbigo. Postura fixa, lombar protegida pelo banco.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Sentar com o peito apoiado no banco. Puxar o cabo para baixo, contrair as escápulas. Nunca rodar o tronco.',
    substitutions: ['puxada-frontal-001'],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'remada-unilateral-001',
    name: 'Remada Unilateral (máquina)',
    muscleGroup: 'costas',
    description: 'Remada com um braço de cada vez. Simetria e correção de desequilíbrios.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Ajustar o banco. Puxar com um braço, contrair o dorsal. Alternar. Manter o tronco estável.',
    substitutions: ['remada-sentada-001'],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'pullover-001',
    name: 'Pullover (máquina)',
    muscleGroup: 'costas',
    description: 'Amplitude de ombros com dorsais. Controlo total da amplitude.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Ajustar o banco. Braços estendidos atrás da cabeça, puxar para baixo controlando os dorsais. Nunca forçar os ombros.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'face-pull-001',
    name: 'Face Pull (cabo)',
    muscleGroup: 'costas',
    description: 'Puxar o cabo em direção à face. Fortalecimento dos rotadores externos e postura.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Cabo à altura da face. Puxar com cotovelos altos, abrir os ombros. Controlar na descida.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'hyperextension-001',
    name: 'Hiperextensão Lombar (máquina)',
    muscleGroup: 'costas',
    description: 'Fortalecimento específico dos eretores da espinha. ESSENCIAL para lombar saudável.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Ajustar o banco para o quadril ficar livre. Descer o tronco até 90º. Subir com a lombar, nunca forçar demais.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },

  // ============================================
  // PEITO
  // ============================================
  {
    id: 'peito-maquina-001',
    name: 'Peito (máquina)',
    muscleGroup: 'peito',
    description: 'Press peito em máquina. Controlo total, sem risco de lombar.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Ajustar o banco para os punhos alinhados com os mamilos. Empurrar controlado, contrair o peito no topo. Nunca travar os cotovelos.',
    substitutions: ['peito-inclinado-001'],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'peito-inclinado-001',
    name: 'Peito Inclinado (máquina)',
    muscleGroup: 'peito',
    description: 'Press peito inclinado. Foco no peito superior e deltoide anterior.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Banco inclinado 30-45º. Empurrar controlado, focar no peito superior. Cotovelos ligeiramente abertos.',
    substitutions: ['peito-maquina-001'],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'crossover-001',
    name: 'Crossover (cabo)',
    muscleGroup: 'peito',
    description: 'Abertura de cabos. Amplitude total do peito, sem carga lombar.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Cabos altos. Abrir os braços controlado, sentir o alongamento do peito. Fechar com os cotovelos ligeiramente flexionados.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'peck-deck-001',
    name: 'Peck Deck (máquina)',
    muscleGroup: 'peito',
    description: 'Abertura de peito em máquina. Isolamento perfeito do peito.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Ajustar o banco para os cotovelos alinhados com os ombros. Juntar os braços controlado, contrair o peito. Nunca forçar.',
    substitutions: ['crossover-001'],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'flexoes-001',
    name: 'Flexões (bodyweight)',
    muscleGroup: 'peito',
    description: 'Flexões no chão. Excelente para força funcional e core.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'bodyweight',
    instructions: 'Mãos na largura dos ombros. Descer até o peito quase tocar o chão. Manter o corpo numa linha reta. Nunca arquear a lombar.',
    substitutions: ['peito-maquina-001'],
    isCustom: false,
    createdAt: new Date(),
  },

  // ============================================
  // BRAÇOS
  // ============================================
  {
    id: 'rosca-biceps-001',
    name: 'Rosca Bíceps (máquina)',
    muscleGroup: 'braços',
    description: 'Rosca bíceps em máquina. Isolamento sem carga lombar.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Ajustar o banco. Cotovelos fixos junto ao corpo. Flexionar o antebraço, contrair o bíceps no topo. Descer controlado.',
    substitutions: ['rosca-haltere-001'],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'rosca-haltere-001',
    name: 'Rosca Bíceps com Halteres (peso livre)',
    muscleGroup: 'braços',
    description: 'Rosca bíceps com halteres. Peso livre para maior controlo.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'peso livre',
    instructions: 'Cotovelos fixos junto ao corpo. Nunca balançar o tronco. Flexionar, contrair, descer controlado.',
    substitutions: ['rosca-biceps-001'],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'triceps-corda-001',
    name: 'Tríceps Corda (cabo)',
    muscleGroup: 'braços',
    description: 'Extensão de tríceps com corda. Excelente para todos os cabeças do tríceps.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Cotovelos fixos junto ao corpo. Estender os braços, separar as cordas no fim. Descer controlado.',
    substitutions: ['triceps-maquina-001'],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'triceps-maquina-001',
    name: 'Tríceps (máquina)',
    muscleGroup: 'braços',
    description: 'Extensão de tríceps em máquina. Isolamento total.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Ajustar o banco. Cotovelos alinhados com o eixo da máquina. Estender, contrair, descer controlado.',
    substitutions: ['triceps-corda-001'],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'triceps-frances-001',
    name: 'Tríceps Francês (haltere)',
    muscleGroup: 'braços',
    description: 'Tríceps francês com halteres. Cuidado com a amplitude dos ombros.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'peso livre',
    instructions: 'Deitado no banco. Halteres acima da cabeça. Flexionar os cotovelos, descer os halteres junto às orelhas. Estender.',
    substitutions: ['triceps-corda-001'],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'rosca-martelo-001',
    name: 'Rosca Martelo (halteres)',
    muscleGroup: 'braços',
    description: 'Rosca martelo para bíceps e braquial. Peso livre, controlo total.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'peso livre',
    instructions: 'Palmas viradas uma para a outra. Cotovelos fixos. Flexionar, descer controlado.',
    substitutions: ['rosca-biceps-001'],
    isCustom: false,
    createdAt: new Date(),
  },

  // ============================================
  // OMBROS
  // ============================================
  {
    id: 'elevacao-lateral-001',
    name: 'Elevação Lateral (máquina)',
    muscleGroup: 'ombros',
    description: 'Elevação lateral em máquina. Isolamento do deltoide médio, sem carga lombar.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Ajustar o banco. Braços junto ao corpo. Elevar até 90º, descer controlado. Nunca usar impulso.',
    substitutions: ['elevacao-lateral-haltere-001'],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'elevacao-lateral-haltere-001',
    name: 'Elevação Lateral com Halteres',
    muscleGroup: 'ombros',
    description: 'Elevação lateral com halteres. Peso livre para maior controlo.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'peso livre',
    instructions: 'Pés na largura dos ombros. Elevar os halteres até 90º, ligeira inclinação para a frente. Descer controlado.',
    substitutions: ['elevacao-lateral-001'],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'desenvolvimento-ombros-001',
    name: 'Desenvolvimento de Ombros (máquina)',
    muscleGroup: 'ombros',
    description: 'Press de ombros em máquina. Controlo total, lombar protegida.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Ajustar o banco. Empurrar para cima controlado, nunca travar os cotovelos. Descer até 90º.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'elevacao-frontal-001',
    name: 'Elevação Frontal (cabo)',
    muscleGroup: 'ombros',
    description: 'Elevação frontal com cabo. Foco no deltoide anterior.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Cabo baixo. Elevar os braços à frente até 90º. Controlar na descida.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },

  // ============================================
  // CORE / LOMBAR
  // ============================================
  {
    id: 'prancha-001',
    name: 'Prancha (bodyweight)',
    muscleGroup: 'core',
    description: 'Prancha abdominal. Fortalecimento do core profundo, essencial para proteção da lombar.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'bodyweight',
    instructions: 'Antebraços no chão, corpo numa linha reta. Contrair o abdómen e glúteos. Manter 30-60 segundos. Nunca arquear a lombar.',
    substitutions: ['prancha-lateral-001'],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'prancha-lateral-001',
    name: 'Prancha Lateral (bodyweight)',
    muscleGroup: 'core',
    description: 'Prancha lateral. Fortalecimento dos oblíquos e estabilidade do tronco.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'bodyweight',
    instructions: 'Deitado de lado, antebraço no chão. Elevar o quadril, corpo numa linha reta. Manter 20-40 segundos cada lado.',
    substitutions: ['prancha-001'],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'bird-dog-001',
    name: 'Bird Dog (bodyweight)',
    muscleGroup: 'core',
    description: 'Quadrupedia com extensão alternada de braço e perna. Excelente para estabilidade lombar e equilíbrio.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'bodyweight',
    instructions: 'De 4 apoios. Estender braço direito e perna esquerda, manter equilíbrio. Trocar. Manter quadril estável.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'bridge-001',
    name: 'Bridge (bodyweight)',
    muscleGroup: 'core',
    description: 'Elevação do quadril deitado. Fortalecimento de glúteos e core posterior.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'bodyweight',
    instructions: 'Deitado de costas, joelhos flexionados. Elevar o quadril, contrair glúteos no topo. Manter 2-3 segundos. Descer.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'vacuo-abdominal-001',
    name: 'Vácuo Abdominal (bodyweight)',
    muscleGroup: 'core',
    description: 'Contração do transverso abdominal. Melhora postura, controlo lombar e estética.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'bodyweight',
    instructions: 'De pé, expirar totalmente. Puxar o umbigo para dentro e para cima, em direção à coluna. Manter 10-20 segundos.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'dead-bug-001',
    name: 'Dead Bug (bodyweight)',
    muscleGroup: 'core',
    description: 'Deitado de costas com extensão alternada de braços e pernas. Core profundo, lombar protegida.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'bodyweight',
    instructions: 'Deitado, braços e pernas para cima. Baixar braço direito e perna esquerda, manter a lombar colada ao chão. Trocar.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },

  // ============================================
  // MOBILIDADE
  // ============================================
  {
    id: 'rotacao-quadril-001',
    name: 'Rotação de Quadril (bodyweight)',
    muscleGroup: 'mobilidade',
    description: 'Rotação controlada do quadril em pé. Melhora amplitude e preparação para treino.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'bodyweight',
    instructions: 'De pé, mãos na cintura. Rodar o quadril em círculos amplos, 10 repetições cada sentido. Manter o tronco estável.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'abertura-tornozelo-001',
    name: 'Abertura de Tornozelo (bodyweight)',
    muscleGroup: 'mobilidade',
    description: 'Mobilidade do tornozelo em apoio na parede. Essencial para squat, equilíbrio e prevenção de quedas.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'bodyweight',
    instructions: 'Frente à parede, um pé à frente. Flexionar o joelho até tocar a parede, manter o calcanhar no chão. 10 reps cada pé.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'mobilidade-ombros-001',
    name: 'Mobilidade de Ombros (cabo)',
    muscleGroup: 'mobilidade',
    description: 'Rotação de ombros com cabo baixo. Amplitude e preparação para treino de costas/peito.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Cabo baixo. Segurar com uma mão, rodar o braço em círculo amplo. 10 reps cada braço, cada sentido.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'thoracic-rotation-001',
    name: 'Rotação Torácica (bodyweight)',
    muscleGroup: 'mobilidade',
    description: 'Rotação da coluna torácica deitado. Alivia tensão lombar, melhora postura.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'bodyweight',
    instructions: 'Deitado de lado, joelhos flexionados 90º. Abrir o braço superior, rodar o tronco. Manter joelhos no chão. 10 reps cada lado.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'cat-cow-001',
    name: 'Cat-Cow (bodyweight)',
    muscleGroup: 'mobilidade',
    description: 'Flexão/extensão da coluna de 4 apoios. Mobilidade lombar controlada, sem carga.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'bodyweight',
    instructions: 'De 4 apoios. Inspirar, arquear a lombar (cow). Expirar, arredondar a coluna (cat). 10 reps, lento e controlado.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: '9090-hip-001',
    name: '90/90 Hip Stretch (bodyweight)',
    muscleGroup: 'mobilidade',
    description: 'Abertura de quadril sentado. Melhora rotação interna/externa, essencial para squat e postura.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'bodyweight',
    instructions: 'Sentado, pernas em 90/90. Inclinar para a frente suavemente, sentir o alongamento no quadril. Manter 30 segundos cada lado.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },

  // ============================================
  // EQUILÍBRIO
  // ============================================
  {
    id: 'single-leg-balance-001',
    name: 'Equilíbrio Unipodal (bodyweight)',
    muscleGroup: 'equilíbrio',
    description: 'Ficar num só pé, olhos abertos/fechados. Fortalecimento de tornozelos, glúteos médio, propriocepção.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'bodyweight',
    instructions: 'De pé, levantar um pé. Manter equilíbrio 30-60 segundos. Progressão: olhos fechados, superfície instável. Nunca apoiar-se.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'half-kneeling-press-001',
    name: 'Half-Kneeling Press (halteres)',
    muscleGroup: 'equilíbrio',
    description: 'Press de ombros ajoelhado. Desafio de equilíbrio + força de ombros.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'peso livre',
    instructions: 'Ajoelhado, um pé à frente. Press de halteres com controlo. Manter o tronco vertical, nunca arquear.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'single-leg-deadlift-001',
    name: 'Single-Leg Deadlift (halteres)',
    muscleGroup: 'equilíbrio',
    description: 'Deadlift unipodal com halteres. Equilíbrio, força posterior, controlo lombar.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'peso livre',
    instructions: 'Um pé, halteres na mão. Inclinar para a frente, estender a perna para trás. Manter a lombar neutra. Peso leve.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
  {
    id: 'pallof-press-001',
    name: 'Pallof Press (cabo)',
    muscleGroup: 'equilíbrio',
    description: 'Press anti-rotação com cabo. Core, equilíbrio, proteção lombar.',
    isLumbarSafe: true,
    isKneeSafe: true,
    type: 'máquina',
    instructions: 'Lateral ao cabo, segurar com as duas mãos. Estender os braços, resistir à rotação. Manter 2-3 segundos. Trocar lado.',
    substitutions: [],
    isCustom: false,
    createdAt: new Date(),
  },
];

export const getDefaultExercises = (): Exercise[] => {
  return DEFAULT_EXERCISES.map((e) => ({
    ...e,
    id: e.id, // manter IDs fixos para referência
  }));
};
